/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Oswaldo
 */
public class Principal extends javax.swing.JFrame {

    //String parse;
    /**
     * Array que maneja todos los datos de entrada
     */
    ArrayList<String> datos = new ArrayList<>();
    /**
     * Variable para manejar la clave ingresada por el usuario
     */
    String claveEntrada = "";
    /**
     * Bandera para saber si estamos cifrando = TRUE si descifra = FALSE
     */
    boolean cifrar = true;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        /**
         * Utilizado para agrupar los Radio button
         */
        ButtonGroup group = new ButtonGroup();
        group.add(rboCifrado);
        group.add(rboDescifrado);
        inicializaFiles();
    }

    /**
     * Borra los archivos de salida que se crearon previamente
     */
    private void inicializaFiles() {
        try {
            File f = new File("salidatrue.txt");
            if (f.exists()) {
                f.delete();
            }
            f = new File("salidafalse.txt");
            if (f.exists()) {
                f.delete();
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rboCifrado = new javax.swing.JRadioButton();
        rboDescifrado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEntrada = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSalida = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtClaveSalida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rboCifrado.setSelected(true);
        rboCifrado.setText("Cifrado");
        rboCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboCifradoActionPerformed(evt);
            }
        });

        rboDescifrado.setText("Descifrado");

        jLabel2.setText("Cifrar / Descifrar:");

        txtAreaEntrada.setColumns(20);
        txtAreaEntrada.setRows(5);
        jScrollPane1.setViewportView(txtAreaEntrada);

        jLabel3.setText("Clave");

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        jButton1.setText("Cifrar o Descifrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Texto Cifrado");

        txtAreaSalida.setEditable(false);
        txtAreaSalida.setColumns(20);
        txtAreaSalida.setRows(5);
        jScrollPane2.setViewportView(txtAreaSalida);

        jLabel5.setText("Clave Salida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(rboDescifrado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(txtClave)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtClaveSalida))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rboCifrado)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboDescifrado)
                    .addComponent(rboCifrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClaveSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 390));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Salida"));

        txtAreaOutput.setColumns(20);
        txtAreaOutput.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtAreaOutput.setRows(5);
        jScrollPane3.setViewportView(txtAreaOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 340, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cifrado de Feistel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Cargar archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rboCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboCifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rboCifradoActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed
    /**
     * Controla la mayor parte de los eventos realizados con el boton
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Cifrar c = new Cifrar(this);
        //Limpio los cuadros de texto
        txtAreaSalida.setText("");
        txtClaveSalida.setText("");
        txtAreaOutput.setText("");
        datos.clear();
        datos = dividirTexto(txtAreaEntrada.getText());
        System.out.println(datos.size());
        if (rboDescifrado.isSelected()) {
            cifrar = false;
            writeToOutput("Inicio Cifrado...");
        } else {
            cifrar = true;
            writeToOutput("Inicio Descifrado...");
        }
        //Revisar clave
        writeToOutput("Revisando clave");
        if (txtClave.getText().length() == 8) {
            claveEntrada = txtClave.getText();
        } else if (txtClave.getText().length() < 8) {
            writeToOutput("Clave menor a 8 agrego espacios");
            claveEntrada = c.agregarEspacios(txtClave.getText(), 8);
        } else {
            writeToOutput("Clave mayor a 8, tomo solo 8 caracteres");
            claveEntrada = txtClave.getText().substring(0, 8);
        }
        System.out.println("Clave Entrada: " + claveEntrada);
        writeToOutput("Clave Entrada: " + claveEntrada);
        
        ArrayList<Integer> cifrado = new ArrayList<>();
        for (int i = 0; i < datos.size(); i++) {
            String dato = datos.get(i);
            //Paso 0. Agregar espacios si es necesario al texto
            if (dato.length() < 16) {
                //datos.remove(i);
                writeToOutput("Tamaño menor a esperado, agregando espacios...");
                datos.set(i, c.agregarEspacios(dato, 16));
            }
            

            //Paso 1. Texto a Ascii
            ArrayList<Integer> asciisTexto = c.convertirAscii(datos.get(i));
            ArrayList<Integer> asciisClave = c.convertirAscii(claveEntrada);
            //System.out.println("SIZES: "+asciisClave.size()+" "+ asciisTexto.size());
            //ArrayList<Integer> cifrado=new ArrayList<>(datos.size()*16);
            //Paso 2. Ascii operaciones
            int pasos = 8;
            while (pasos > 0) {
                for (int j = 8; j < asciisTexto.size(); j++) {
                    Integer td = asciisTexto.get(j);
                    Integer cl = asciisClave.get(j - 8);
                    Integer ti = asciisTexto.get(j - 8);
                    //System.out.println("Asciis " + td + " " + cl);
                    //Paso 3. Derecha con clave
                    Integer result;
                    if (cifrar) {
                        result = td ^ cl;
                        if (result >= 256) {
                            result = result - 256;
                        }
                    } else {
                        result = ti ^ cl;
                        if (result >= 256) {
                            result = result - 256;
                        }
                    }

                    //System.out.println("Resultado: " + result);
                    //System.out.println("Asciis " + result + " " + ti);
                    //Paso 4. Resultado con Izquierda
                    if (cifrar) {
                        result = result ^ ti;
                        if (result >= 256) {
                            result = result - 256;
                        }
                    } else {
                        result = result ^ td;
                        if (result >= 256) {
                            result = result - 256;
                        }
                    }

                    //System.out.println("Resultado: " + result);
                    if (cifrar) {
                        for (int k = 8; k < 16; k++) {
                            Integer td2 = asciisTexto.get(k);
                            if (cifrado.size() >= 8) {
                                break;
                            } else {
                                cifrado.add((k - 8), td2);
                            }
                        }
                        cifrado.add(j, result);
                    } else {
                        cifrado.add((j - 8), result);

                    }

                }
                //Paso 5. Resultado a izquierda y el otro a derecha
                for (int j = 8; j < asciisTexto.size(); j++) {
                    Integer ti;
                    if (!cifrar) {
                        ti = asciisTexto.get(j - 8);
                        cifrado.add(j /*+ (j * i)*/, ti);
                    }
                }

                escribirArchivo(cifrar, "=======================================");
                //System.out.println("=======================================");
                //System.out.println("Paso " + (9 - pasos) + ":  ");
                escribirArchivo(cifrar, "Paso " + (9 - pasos) + ":  ");
                //System.out.println("=======================================");
                escribirArchivo(cifrar, "=======================================");
                escribirArchivo(cifrar, "Texto Entrada: ");
                //System.out.println("Texto Entrada: ");
                
                
                writeToOutput("==================");;
                writeToOutput("Paso " + (9 - pasos) + ":  ");
                writeToOutput("==================");;
                writeToOutput("Texto entrada: ");
                
                imprimirParte(asciisTexto);
                
                //System.out.println(asciisTexto.toString());
                escribirArchivo(cifrar, asciisTexto.toString());
                //System.out.println("Clave paso: ");
                escribirArchivo(cifrar, "Clave paso: ");
                
                //System.out.println(asciisClave.toString());
                escribirArchivo(cifrar, asciisClave.toString());
                
                writeToOutput("Clave paso: ");
                
                imprimirParte(asciisClave);

                asciisTexto.clear();
                asciisTexto = new ArrayList<Integer>(cifrado);

                escribirArchivo(cifrar, "Texto Cifrado:");
                System.out.println("Texto Cifrado:");
                
                //System.out.println(cifrado.toString());
                escribirArchivo(cifrar, cifrado.toString());
     
                writeToOutput("Texto Cifrado:");
     
                imprimirParte(cifrado);

                pasos--;
                
                if (pasos == 0) {
                    //txtAreaSalida.setText("");
                    txtClaveSalida.setText("");
                    for (Integer cifrado1 : cifrado) {
                        txtAreaSalida.setText(txtAreaSalida.getText() + Character.toChars(cifrado1)[0]);
                    }
                    for (Integer asciisClave1 : asciisClave) {
                        txtClaveSalida.setText(txtClaveSalida.getText() + Character.toChars(asciisClave1)[0]);
                    }
                    if (!cifrar) {
                        txtAreaSalida.setText(txtAreaSalida.getText().trim());
                    }
                    cifrado.clear();
                    break;
                } else {
                    cifrado.clear();
                    //Paso 6. Mover circularmente la clave
                    asciisClave = c.rotacionCircular(asciisClave, cifrar);
                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            String CompleteFileName="";
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Text files","txt");
            chooser.setFileFilter(filter);
            int returnVal = chooser.showOpenDialog(this);
            if(returnVal == JFileChooser.APPROVE_OPTION) {
               CompleteFileName=chooser.getSelectedFile().getAbsolutePath();
               txtAreaEntrada.setText(Cifrar.ReadFromFile(CompleteFileName, "UTF8"));
            }
        }catch (Exception e){
             JOptionPane.showMessageDialog(this,
            "Error en lectura de archivo " + e.getMessage(),
            "Error de lectura",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Utilizado para imprimir las partes de texto ingresadas
     *
     * @param entrada Texto a imprimir
     */
    public void imprimirParte(ArrayList<Integer> entrada) {
        for (int entrada1 : entrada) {
            System.out.print(Character.toChars(entrada1)[0]);
    
            txtAreaOutput.append(Character.toString ((char) entrada1));
        }
        txtAreaOutput.append("\n");
        System.out.println("");
    }

    /**
     * Divide el texto en pedazos de 16 caracteres
     *
     * @param text el texto total a separar para luego codificar
     * @return Regresa un array con el total de textos con 16 caracteres
     */
    public static ArrayList<String> dividirTexto(String text) {
        // Give the list the right capacity to start with. You could use an array
        // instead if you wanted.
        ArrayList<String> ret = new ArrayList<>((text.length() + 16 - 1) / 16);
        for (int start = 0; start < text.length(); start += 16) {
            ret.add(text.substring(start, Math.min(text.length(), start + 16)));
        }
        return ret;
    }

    /**
     * Escribe archivo de entrada o salida segun la seleccion del comboBox
     *
     * @param cifra varibale que establece si se esta cifrando o descifrando
     * @param texto el texto que se va escribir
     */
    public void escribirArchivo(boolean cifra, String texto) {
        try {
            File f = new File("salida" + cifra + ".txt");
            FileWriter fw = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.append(texto);
            bw.newLine();
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void writeToOutput(String output) {
        txtAreaOutput.append(output + "\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
 
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rboCifrado;
    private javax.swing.JRadioButton rboDescifrado;
    private javax.swing.JTextArea txtAreaEntrada;
    private javax.swing.JTextArea txtAreaOutput;
    private javax.swing.JTextArea txtAreaSalida;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClaveSalida;
    // End of variables declaration//GEN-END:variables

}
